### ISSUE TITLE
Help, how can i fix this?

### ISSUE THREAD

**Issue by DragonOfStendarr** [TeamWizardry/Wizardry#115]
Caught exception from Wizardry (wizardry)
Caused by: java.lang.NoClassDefFoundError: com/teamwizardry/wizardry/common/item/ItemBook
	at com.teamwizardry.wizardry.proxy.CommonProxy.preInit(CommonProxy.java:54)
	at com.teamwizardry.wizardry.proxy.ClientProxy.preInit(ClientProxy.java:49)
	at com.teamwizardry.wizardry.Wizardry.preInit(Wizardry.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:6

**Comment by Demoniaque** [comment]
update Liblib
