### ISSUE TITLE
Using Empty Syringe Causes Fatal Crash

### ISSUE THREAD

**Issue by KittenKoder** [TeamWizardry/Wizardry#156]
This is in single player, and here is the error from the log:

`java.lang.NullPointerException: Ticking player
	at com.teamwizardry.wizardry.common.item.ItemSyringe.onUsingTick(ItemSyringe.java:91)
	at net.minecraft.entity.EntityLivingBase.func_184608_ct(EntityLivingBase.java:2668)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2088)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by Demoniaque** [comment]
Most probably fixed in the next update
