### ISSUE TITLE
Crashing on loading world.

### ISSUE THREAD

**Issue by BloodravenD** [TeamWizardry/Wizardry#170]
I was crafting a spell, and after saving the spell it crashed the game.  I updated the mod, assumed it was because of an older version of the mod(0.8.5), now whenever I try to load my world, it crashes with this error:

PM
Description: Rendering Block Entity

java.lang.NoClassDefFoundError: com/teamwizardry/librarianlib/features/math/interpolate/numeric/InterpFloatInOut
	at com.teamwizardry.wizardry.client.fx.LibParticles.CRAFTING_ALTAR_IDLE(LibParticles.java:253)
	at com.teamwizardry.wizardry.client.render.block.TileCraftingPlateRenderer.render(TileCraftingPlateRenderer.java:160)
	at com.teamwizardry.librarianlib.features.tesr.TESRMod.render(TESRMod.kt:41)
	at com.teamwizardry.librarianlib.features.tesr.TESRMod.func_192841_a(TESRMod.kt:14)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_192854_a(TileEntityRendererDispatcher.java:155)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:130)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:705)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1347)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.teamwizardry.librarianlib.features.math.interpolate.numeric.InterpFloatInOut
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 19 more
Caused by: java.lang.NullPointerException

Im currently using forge-14.23.4.2747, and the modpack I'm using is All The Mods 3.

I've tried 0.9.5 and 0.9.4 version of the Wizardry mod and both have this same issue.

**Comment by murapix** [comment]
Update LibLib

**Comment by BloodravenD** [comment]
Librarian Lib?  I'm already using 1.12.2-4.12 of that.

**Comment by yrsegal** [comment]
you're definitely not using 4.12, if that's your crash.

**Comment by BloodravenD** [comment]
It said in the mods folder that it was 4.12, and in the twitch client it said 4.12, but the crash log said 4.9 for some reason.  I chose 4.11 then back to 4.12, just in the off chance downloading it was what broke it.  Fixed the issue.
