### ISSUE TITLE
Errors when server startup

### ISSUE THREAD

**Issue by pingvikin** [TeamWizardry/Wizardry#171]
I have a some errors in console, when my server is startup.

**Full server log**: https://gist.github.com/pingvikin/ecd23003f71ac61a5397c92733396a06

**Error message:**
[14:22:25] [Server thread/ERROR] [FML]: Parsing error loading recipe wizardry:syringe/fill_mana_syringe
com.google.gson.JsonSyntaxException: Unknown item 'wizardry:mana_orb'
	at net.minecraftforge.common.crafting.CraftingHelper.getItemStackBasic(CraftingHelper.java:260) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.lambda$init$16(CraftingHelper.java:537) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.getIngredient(CraftingHelper.java:202) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.lambda$init$15(CraftingHelper.java:524) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.getRecipe(CraftingHelper.java:409) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.lambda$loadRecipes$22(CraftingHelper.java:711) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:822) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:668) ~[CraftingHelper.class:?]
	at java.util.ArrayList.forEach(ArrayList.java:1249) [?:1.8.0_72]
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:620) [CraftingHelper.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742) [Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108) [FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:337) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

**Comment by Demoniaque** [comment]
Update the mod + LibLib

**Comment by pingvikin** [comment]
I have latest version of mod and LibLib

**Comment by pingvikin** [comment]
@Demoniaque I have latest version of mod and LibLib

**Comment by Demoniaque** [comment]
Where did you get the mod jar from? Did you get it from curseforge like you're supposed to?

**Comment by pingvikin** [comment]
Yes

**Comment by murapix** [comment]
Fixed in 0a056b7

**Comment by yrsegal** [comment]
We renamed the item, demoniaque.
