### ISSUE TITLE
Server hard lockup ASMEventHandler_973_PotionPhase_entityMove_EntityMoveEvent.invoke()100.00%

### ISSUE THREAD

**Issue by ProsperCraft** [TeamWizardry/Wizardry#204]
I think someone got access to one of your potion effects thorough Tombstone halloween event candy that can give any random potion effect.

Here is a warmroast screenshot, and find also attached the warmroast page if you desire.

![d1cc52882f213053175471332c3902d1](https://user-images.githubusercontent.com/4427684/47572280-d4973080-d8f7-11e8-968f-08f5ff6224e0.png)

[wizardrylockup.zip](https://github.com/TeamWizardry/Wizardry/files/2519539/wizardrylockup.zip)

**Comment by ProsperCraft** [comment]
It locked up hard again, please look into this.
Warmroast-
![aca0dd967f43c41a9b48805af66e531f](https://user-images.githubusercontent.com/4427684/48428300-f8e07300-e727-11e8-8315-7c6c710574fb.png)

Latest Stall report-
https://gist.github.com/ProsperCraft/8169eb8fe5b2709e2a88ba56772cec87

**Comment by ProsperCraft** [comment]
[lockup.zip](https://github.com/TeamWizardry/Wizardry/files/2577178/lockup.zip)

All stall reports and warmroast page.

**Comment by NachtRaveVL** [comment]
+1 having the same issue.

```
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185890_d(BlockStateContainer.java:446)
	at net.minecraft.block.Block.func_185477_a(Block.java:460)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185908_a(BlockStateContainer.java:451)
	at net.minecraft.world.World.func_191504_a(World.java:1338)
	at net.minecraft.world.World.func_184144_a(World.java:1362)
	at com.teamwizardry.wizardry.common.potion.PotionPhase.entityMove(PotionPhase.java:83)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1862_PotionPhase_entityMove_EntityMoveEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at com.teamwizardry.wizardry.asm.WizardryASMHooks.entityPreMoveHook(WizardryASMHooks.java:27)
	at net.minecraft.entity.Entity.func_70091_d(Entity.java)
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:545)
	at net.minecraft.network.play.client.CPacketPlayer.func_148833_a(SourceFile:126)
	at net.minecraft.network.play.client.CPacketPlayer$PositionRotation.func_148833_a(SourceFile:18)
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at net.minecraft.util.Util.func_181617_a(SourceFile:46)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
```

**Comment by PhotonChaos** [comment]
That's pretty bizarre. Unfortunately, since we can't reproduce this issue we can't fix it. If anyone is having this issue with the newest version of Wizardry and LibLib, please comment on this issue with the steps you took to reproduce it, and we will look into it.
