### ISSUE TITLE
Server crash on startup but works in solo

### ISSUE THREAD

**Issue by PyroEnder** [TeamWizardry/Wizardry#220]
First, i want to apologize if there're mistakes, i'm not english.

The server doesn't crash but its window is closed and there is not crash report created.
I'm using a custom modpack.

Thank for your help

PS: here's the latest log files created after the crash
[latest.log](https://github.com/TeamWizardry/Wizardry/files/2635798/latest.log)

**Comment by SaadArdati** [comment]
Where did you get your librarianlib jar from? Are you sure you're using liblib version 4.15 or above?

**Comment by Bluexin** [comment]
@PyroEnder Retires l'accent dans ton nom de dossier, et réessayes. Si ça ne fonctionne pas, télécharges LibrarianLib depuis [le lien officiel](https://minecraft.curseforge.com/projects/librarianlib/files/2613851/download) et réessayes. Si c'est toujours pas bon, envoies le nouveau log (via pastebin/hastebin/...).

*Remove the accent in your folder name and try again. If it doesn't work, download LibrarianLib from [the official link](https://minecraft.curseforge.com/projects/librarianlib/files/2613851/download) and retry. If it's still not working, send the new log over (via pastebin/hastebin/...)*

**Comment by PyroEnder** [comment]
Désolé pour le temps de réponse assez long, je tenais à m'excusé.
 Du coup,j'ai supprimé l'accent dans le nom du dossier et installé la
version de LibrarianLib qui est dans le mail mais le problème persiste donc
voici le log. (en verion rar)

I wanted to apologize for the respond time which was quite long, sorry
about that.
So I've deleted the accent and installed the version of LibrarianLib you
sent me but it still doesn't work so here is the log file. (rar version)

Le mar. 4 déc. 2018 à 16:11, Arnaud Solé <notifications@github.com> a
écrit :

**Comment by Bluexin** [comment]
Les pièces jointes par mail ne passent pas sur GitHub, et en rar c'est encore pire que juste le fichier de log. Copie-colles le contenu sur pastebin et envoies le lien.

*Mailed attachments don't go trough to GitHub, and rar is even worse than just the log file. Copy-paste it on pastebin and send us the link.*

**Comment by PyroEnder** [comment]
impossible de copier coller sur pastebin...
voici le fichier "latest" dans le dossier log ( désolé mais je suppose que
c'est mieux que rien)

impossible to copy paste on pastebin...
here's the folder named "latest" in the log folder (i'm sorry but i guess
it's better than nothing)

Le mar. 4 déc. 2018 à 18:57, Arnaud Solé <notifications@github.com> a
écrit :

**Comment by Bluexin** [comment]
> Les pièces jointes par mail ne passent pas sur GitHub, et en rar c'est encore pire que juste le fichier de log. Copie-colles le contenu sur pastebin et envoies le lien.
> 
> _Mailed attachments don't go trough to GitHub, and rar is even worse than just the log file. Copy-paste it on pastebin and send us the link._

Il faut que tu ouvres l'issue sur GitHub et nous donnes le fichier ici, l'ajouter en pièce jointe ne sert à rien (on ne le reçoit pas).

*You have to open the issue on GitHub and send the file over this way, joining it to the mail is useless (we won't receive it).*

**Comment by PyroEnder** [comment]
voici le lien du fichier "latest.log"

here is the link for "latest.log"

http://pastebin.de/12764/

Le mar. 4 déc. 2018 à 20:20, Arnaud Solé <notifications@github.com> a
écrit :

**Comment by PyroEnder** [comment]
j'ai oublier de dire que j'arrivais a jouer en solo, c'est juste sur le
serveur que plante

I forget to mention that i can play in solo, there is crash only on the
server

**Comment by Bluexin** [comment]
```
[20:53:54] [Server thread/INFO] [STDERR]: [com.teamwizardry.librarianlib.features.autoregister.AnnotationMarkersHandler:handle:87]: kotlin.KotlinNullPointerException
at kotlin.reflect.jvm.internal.KPropertyImplKt.computeCallerForAccessor(KPropertyImpl.kt:243)
at kotlin.reflect.jvm.internal.KPropertyImplKt.access$computeCallerForAccessor(KPropertyImpl.kt:1)
at kotlin.reflect.jvm.internal.KPropertyImpl$Getter$caller$2.invoke(KPropertyImpl.kt:157)
at kotlin.reflect.jvm.internal.KPropertyImpl$Getter$caller$2.invoke(KPropertyImpl.kt:148)
at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:93)
at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)
at kotlin.reflect.jvm.internal.KPropertyImpl$Getter.getCaller(KPropertyImpl.kt)
at kotlin.reflect.jvm.ReflectJvmMapping.getJavaMethod(ReflectJvmMapping.kt:62)
at kotlin.reflect.jvm.ReflectJvmMapping.getJavaGetter(ReflectJvmMapping.kt:47)
at com.teamwizardry.librarianlib.features.saving.SavingFieldCache.createMetaForProperty(SavingFieldCache.kt:276)
at com.teamwizardry.librarianlib.features.saving.SavingFieldCache.buildClassFields(SavingFieldCache.kt:89)
at com.teamwizardry.librarianlib.features.saving.SavingFieldCache.getClassFields(SavingFieldCache.kt:40)
at com.teamwizardry.librarianlib.features.saving.AbstractSaveHandler.cacheFields(AbstractSaveHandler.kt:93)
at com.teamwizardry.librarianlib.features.autoregister.builtin.TileRegisterProcessor.process(RegisterProcessors.kt:38)
at com.teamwizardry.librarianlib.features.autoregister.builtin.TileRegisterProcessor.process(RegisterProcessors.kt:25)
at com.teamwizardry.librarianlib.features.autoregister.AnnotationMarkersHandler.handle(AnnotationMarkers.kt:80)
at com.teamwizardry.librarianlib.features.autoregister.AnnotationMarkersHandler.preInit(AnnotationMarkers.kt:36)
at com.teamwizardry.librarianlib.core.common.LibCommonProxy.latePre(LibCommonProxy.kt:52)
at com.teamwizardry.librarianlib.core.LateLoader.preInit(LateLoader.kt:13)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
at com.google.common.eventbus.EventBus.post(EventBus.java:217)
at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
at com.google.common.eventbus.EventBus.post(EventBus.java:217)
at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99)
at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
at java.lang.Thread.run(Unknown Source)
```
For ref

**Comment by PyroEnder** [comment]
est ce que ça que vous vouliez ?

is that what you wanted ?

Le mar. 4 déc. 2018 à 21:07, Arnaud Solé <notifications@github.com> a
écrit :

**Comment by Bluexin** [comment]
Oui, merci beaucoup :)

**Comment by SaadArdati** [comment]
Wizardry is not mentioned in the crash log, transferring issue to LibrarianLib
