### ISSUE TITLE
Crash upon using the mouse scroll wheel to change hotbar...

### ISSUE THREAD

**Issue by MLMII** [TeamWizardry/Wizardry#269]
I can change my hotbar using the number keys, but the moment I touch my mouse scroll wheel, it crashes with this log...

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Quark Plugin (Quark-r1.5-150.jar)
  GenderLoadingPlugin ([1.12.2]Gender-1.2.9.jar)
  JEIDsILoadingPlugin (jeidsi-1.2.0.22.jar)
  Wizardry Plugin (wizardry-0.10.0.jar)
  JEIDLoadingPlugin (JustEnoughIDs-1.0.2-26.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.17.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 5/9/19 10:23 PM
Description: Unexpected error

java.lang.IllegalArgumentException: Argument is not an array
	at com.teamwizardry.librarianlib.features.saving.ArrayReflect.badArray(ArrayReflect.java:24)
	at com.teamwizardry.librarianlib.features.saving.ArrayReflect.get(ArrayReflect.java:122)
	at com.teamwizardry.librarianlib.features.animator.FieldListItem$rootGetter$2$2.invoke(KeyPathGetterSetterGenerator.kt:187)
	at com.teamwizardry.librarianlib.features.animator.FieldListItem$rootSetter$2$1.invoke(KeyPathGetterSetterGenerator.kt:246)
	at com.teamwizardry.librarianlib.features.animator.FieldListItem$rootSetter$2$1.invoke(KeyPathGetterSetterGenerator.kt:247)
	at com.teamwizardry.librarianlib.features.animator.KeyPathGetterSetterGeneratorKt$generateGetterAndSetterForKeyPath$1.invoke(KeyPathGetterSetterGenerator.kt:89)
	at com.teamwizardry.librarianlib.features.animator.KeyPathGetterSetterGeneratorKt$generateGetterAndSetterForKeyPath$1.invoke(KeyPathGetterSetterGenerator.kt)
	at com.teamwizardry.librarianlib.features.animator.AnimatableProperty.set(AnimatableProperty.kt:27)
	at com.teamwizardry.librarianlib.features.animator.animations.BasicAnimation.update(BasicAnimation.kt:32)
	at com.teamwizardry.librarianlib.features.animator.Animator.update$librarianlib_1_12_2(Animator.kt:146)
	at com.teamwizardry.librarianlib.features.animator.Animator$Companion.renderTick(Animator.kt:205)
	at com.teamwizardry.librarianlib.features.animator.Animator.renderTick(Animator.kt)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_33_Animator_renderTick_RenderTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onRenderTickStart(FMLCommonHandler.java:355)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.teamwizardry.librarianlib.features.saving.ArrayReflect.badArray(ArrayReflect.java:24)
	at com.teamwizardry.librarianlib.features.saving.ArrayReflect.get(ArrayReflect.java:122)
	at com.teamwizardry.librarianlib.features.animator.FieldListItem$rootGetter$2$2.invoke(KeyPathGetterSetterGenerator.kt:187)
	at com.teamwizardry.librarianlib.features.animator.FieldListItem$rootSetter$2$1.invoke(KeyPathGetterSetterGenerator.kt:246)
	at com.teamwizardry.librarianlib.features.animator.FieldListItem$rootSetter$2$1.invoke(KeyPathGetterSetterGenerator.kt:247)
	at com.teamwizardry.librarianlib.features.animator.KeyPathGetterSetterGeneratorKt$generateGetterAndSetterForKeyPath$1.invoke(KeyPathGetterSetterGenerator.kt:89)
	at com.teamwizardry.librarianlib.features.animator.KeyPathGetterSetterGeneratorKt$generateGetterAndSetterForKeyPath$1.invoke(KeyPathGetterSetterGenerator.kt)
	at com.teamwizardry.librarianlib.features.animator.AnimatableProperty.set(AnimatableProperty.kt:27)
	at com.teamwizardry.librarianlib.features.animator.animations.BasicAnimation.update(BasicAnimation.kt:32)
	at com.teamwizardry.librarianlib.features.animator.Animator.update$librarianlib_1_12_2(Animator.kt:146)
	at com.teamwizardry.librarianlib.features.animator.Animator$Companion.renderTick(Animator.kt:205)
	at com.teamwizardry.librarianlib.features.animator.Animator.renderTick(Animator.kt)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_33_Animator_renderTick_RenderTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['MLMII'/380, l='MpServer', x=-126.10, y=64.00, z=370.91]]
	Chunk stats: MultiplayerChunkCache: 4085, 4085
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-240,64,252), Chunk: (at 0,4,12 in -15,15; contains blocks -240,0,240 to -225,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 3012 game time, 3012 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 183 total; [EntitySkeleton['Skeleton'/2305, l='MpServer', x=-136.50, y=14.00, z=405.50], EntityZombie['Zombie'/2306, l='MpServer', x=-116.50, y=37.00, z=381.50], EntityItem['item.item.seeds'/2050, l='MpServer', x=-155.37, y=63.00, z=426.43], EntitySkeleton['Skeleton'/2052, l='MpServer', x=-118.50, y=41.00, z=366.50], EntitySkeleton['Skeleton'/2053, l='MpServer', x=-121.50, y=41.00, z=369.50], EntitySkeleton['Skeleton'/2054, l='MpServer', x=-121.50, y=41.00, z=368.50], EntityCreeper['Creeper'/2312, l='MpServer', x=-115.50, y=37.00, z=379.50], EntityFishSalmon['Salmon'/2317, l='MpServer', x=-134.56, y=62.17, z=379.16], EntityFishSalmon['Salmon'/2318, l='MpServer', x=-131.75, y=62.17, z=378.75], EntityFishSalmon['Salmon'/2319, l='MpServer', x=-139.10, y=62.20, z=380.23], EntityFishSalmon['Salmon'/2578, l='MpServer', x=-189.50, y=61.00, z=375.50], EntityItem['item.item.seeds'/1812, l='MpServer', x=-115.16, y=64.00, z=371.42], EntityItem['item.item.seeds'/1813, l='MpServer', x=-164.54, y=62.00, z=334.80], EntityZombie['Zombie'/2584, l='MpServer', x=-99.50, y=35.00, z=344.50], EntityZombie['Zombie'/2585, l='MpServer', x=-127.43, y=54.00, z=365.75], EntityZombie['Zombie'/2586, l='MpServer', x=-128.50, y=54.00, z=367.50], EntityZombie['Zombie'/2587, l='MpServer', x=-126.50, y=54.00, z=370.50], EntityZombie['Zombie'/284, l='MpServer', x=-204.50, y=28.00, z=308.50], EntitySheep['Sheep'/286, l='MpServer', x=-168.77, y=64.00, z=361.27], EntitySheep['Sheep'/287, l='MpServer', x=-200.23, y=64.00, z=337.81], EntitySheep['Sheep'/288, l='MpServer', x=-191.18, y=64.00, z=346.54], EntitySheep['Sheep'/289, l='MpServer', x=-197.45, y=64.00, z=336.97], EntitySpider['Spider'/1314, l='MpServer', x=-130.50, y=31.00, z=346.50], EntitySheep['Sheep'/290, l='MpServer', x=-196.80, y=87.00, z=414.49], EntitySheep['Sheep'/291, l='MpServer', x=-193.44, y=87.00, z=398.79], EntityItem['item.item.seeds'/1827, l='MpServer', x=-163.37, y=64.00, z=330.02], EntitySheep['Sheep'/292, l='MpServer', x=-191.80, y=87.00, z=410.56], EntitySquid['Squid'/2341, l='MpServer', x=-153.62, y=62.58, z=377.63], EntitySquid['Squid'/2342, l='MpServer', x=-153.13, y=59.03, z=372.21], EntityFishCod['Cod'/2599, l='MpServer', x=-193.50, y=62.00, z=307.50], EntitySquid['Squid'/2343, l='MpServer', x=-149.90, y=60.78, z=430.60], EntityItem['item.item.quark:root_blue_flower'/296, l='MpServer', x=-176.13, y=49.00, z=354.22], EntityFishCod['Cod'/2600, l='MpServer', x=-198.34, y=62.00, z=303.28], EntitySquid['Squid'/2344, l='MpServer', x=-147.21, y=61.69, z=423.44], EntityItem['item.item.seeds'/297, l='MpServer', x=-181.72, y=63.00, z=358.53], EntityFishCod['Cod'/2601, l='MpServer', x=-203.50, y=62.00, z=298.50], EntitySquid['Squid'/2345, l='MpServer', x=-72.39, y=61.02, z=352.29], EntitySheep['Sheep'/298, l='MpServer', x=-180.19, y=72.00, z=378.35], EntitySheep['Sheep'/299, l='MpServer', x=-179.50, y=74.00, z=379.50], EntitySheep['Sheep'/300, l='MpServer', x=-177.54, y=76.00, z=380.27], EntityCreeper['Creeper'/1324, l='MpServer', x=-129.50, y=26.00, z=340.50], EntitySheep['Sheep'/301, l='MpServer', x=-190.50, y=87.00, z=405.50], EntitySquid['Squid'/2350, l='MpServer', x=-105.96, y=62.49, z=309.64], EntitySquid['Squid'/2351, l='MpServer', x=-105.60, y=61.24, z=313.60], EntitySquid['Squid'/2352, l='MpServer', x=-86.23, y=56.00, z=405.85], EntityZombie['Zombie'/2097, l='MpServer', x=-134.50, y=56.00, z=306.50], EntitySquid['Squid'/2353, l='MpServer', x=-89.60, y=56.23, z=402.34], EntityZombie['Zombie'/2098, l='MpServer', x=-136.50, y=56.00, z=305.50], EntitySquid['Squid'/2354, l='MpServer', x=-85.40, y=56.34, z=406.60], EntitySquid['Squid'/2355, l='MpServer', x=-86.42, y=55.62, z=402.40], EntitySheep['Sheep'/308, l='MpServer', x=-166.50, y=64.00, z=294.50], EntitySheep['Sheep'/309, l='MpServer', x=-166.50, y=64.00, z=293.50], EntitySheep['Sheep'/310, l='MpServer', x=-165.50, y=64.00, z=291.50], EntityBat['Bat'/1846, l='MpServer', x=-84.28, y=36.98, z=357.12], EntityBat['Bat'/2614, l='MpServer', x=-110.48, y=21.08, z=311.00], EntitySheep['Sheep'/311, l='MpServer', x=-160.73, y=68.00, z=301.49], EntitySheep['Sheep'/312, l='MpServer', x=-175.50, y=83.00, z=383.50], EntityBat['Bat'/2616, l='MpServer', x=-136.25, y=37.40, z=320.48], EntitySheep['Sheep'/313, l='MpServer', x=-171.50, y=68.00, z=436.50], EntityBat['Bat'/2617, l='MpServer', x=-88.28, y=33.92, z=367.69], EntitySheep['Sheep'/314, l='MpServer', x=-172.50, y=68.00, z=437.50], EntityCreeper['Creeper'/1851, l='MpServer', x=-138.50, y=38.00, z=389.50], EntitySheep['Sheep'/315, l='MpServer', x=-172.50, y=67.00, z=436.50], EntitySheep['Sheep'/316, l='MpServer', x=-168.50, y=68.00, z=432.50], EntityCreeper['Creeper'/2367, l='MpServer', x=-202.50, y=21.00, z=373.50], EntityArcheologist['Archaeologist'/322, l='MpServer', x=-153.00, y=12.00, z=295.00], EntitySheep['Sheep'/323, l='MpServer', x=-147.50, y=47.00, z=314.50], EntitySheep['Sheep'/324, l='MpServer', x=-150.50, y=55.00, z=313.50], EntitySheep['Sheep'/325, l='MpServer', x=-149.51, y=58.00, z=317.27], EntitySheep['Sheep'/326, l='MpServer', x=-155.36, y=62.00, z=309.80], EntityItem['item.item.quark:root_white_flower'/327, l='MpServer', x=-144.69, y=33.00, z=325.78], EntityItem['item.item.seeds'/328, l='MpServer', x=-159.93, y=62.00, z=339.68], EntityItem['item.item.seeds'/1353, l='MpServer', x=-113.35, y=61.00, z=375.56], EntityItem['item.tile.flower2.poppy'/338, l='MpServer', x=-143.68, y=54.00, z=364.17], EntityItem['item.item.seeds'/1363, l='MpServer', x=-151.09, y=63.00, z=367.27], EntityPig['Pig'/340, l='MpServer', x=-114.67, y=63.00, z=303.26], EntityPig['Pig'/342, l='MpServer', x=-115.03, y=63.00, z=304.55], EntitySkeleton['Skeleton'/2646, l='MpServer', x=-55.50, y=26.00, z=371.50], EntityPig['Pig'/343, l='MpServer', x=-117.59, y=64.00, z=304.89], EntitySkeleton['Skeleton'/2647, l='MpServer', x=-54.50, y=26.00, z=372.50], EntityPig['Pig'/344, l='MpServer', x=-114.50, y=63.00, z=306.50], EntityZombie['Zombie'/1369, l='MpServer', x=-114.50, y=22.00, z=307.50], EntityItem['item.item.quark:root'/345, l='MpServer', x=-121.51, y=11.00, z=327.24], EntityFishSalmon['Salmon'/2649, l='MpServer', x=-143.50, y=61.00, z=429.50], EntityFishSalmon['Salmon'/2650, l='MpServer', x=-143.91, y=62.19, z=423.06], EntityFishCod['Cod'/1627, l='MpServer', x=-103.50, y=61.00, z=293.50], EntityFishSalmon['Salmon'/2651, l='MpServer', x=-140.50, y=61.00, z=419.50], EntityFishSalmon['Salmon'/2652, l='MpServer', x=-138.50, y=61.00, z=419.50], EntityZombie['Zombie'/2141, l='MpServer', x=-106.50, y=28.00, z=311.50], EntityPig['Pig'/349, l='MpServer', x=-103.48, y=64.00, z=376.08], EntityFishCod['Cod'/1629, l='MpServer', x=-105.50, y=61.00, z=292.50], EntityFishCod['Cod'/1630, l='MpServer', x=-106.87, y=61.00, z=293.29], EntityPig['Pig'/350, l='MpServer', x=-110.96, y=64.00, z=368.06], EntityPig['Pig'/351, l='MpServer', x=-101.50, y=64.00, z=372.50], EntityItem['item.item.quark:root'/1375, l='MpServer', x=-112.13, y=28.00, z=308.13], EntityZombie['Zombie'/2144, l='MpServer', x=-106.50, y=28.00, z=309.50], EntityPig['Pig'/352, l='MpServer', x=-100.50, y=65.00, z=375.50], EntityCreeper['Creeper'/2145, l='MpServer', x=-107.50, y=28.00, z=310.50], EntityFishSalmon['Salmon'/2657, l='MpServer', x=-107.50, y=60.00, z=293.50], EntityFishSalmon['Salmon'/2658, l='MpServer', x=-106.50, y=60.00, z=295.50], EntityFishSalmon['Salmon'/2659, l='MpServer', x=-106.50, y=60.00, z=296.50], EntityFishSalmon['Salmon'/2660, l='MpServer', x=-104.50, y=60.00, z=297.50], EntityZombie['Zombie'/1894, l='MpServer', x=-155.50, y=39.00, z=302.50], EntityZombie['Zombie'/2150, l='MpServer', x=-197.50, y=26.00, z=344.50], EntitySkeleton['Skeleton'/1896, l='MpServer', x=-144.50, y=45.00, z=309.50], EntityItem['item.item.seeds'/1640, l='MpServer', x=-119.15, y=60.00, z=376.01], EntityZombie['Zombie'/2665, l='MpServer', x=-188.50, y=39.00, z=418.50], EntityRabbit['Rabbit'/617, l='MpServer', x=-52.50, y=69.00, z=425.50], EntitySkeleton['Skeleton'/2666, l='MpServer', x=-146.50, y=42.00, z=337.50], EntityRabbit['Rabbit'/618, l='MpServer', x=-55.50, y=69.00, z=429.10], EntityRabbit['Rabbit'/619, l='MpServer', x=-56.39, y=68.00, z=415.85], EntityZombie['Zombie'/2156, l='MpServer', x=-84.52, y=33.00, z=350.81], EntityChicken['Chicken'/620, l='MpServer', x=-60.50, y=67.00, z=404.50], EntityZombie['Zombie'/2157, l='MpServer', x=-88.50, y=32.00, z=358.50], EntityChicken['Chicken'/621, l='MpServer', x=-58.50, y=66.00, z=406.50], EntityZombie['Zombie'/2158, l='MpServer', x=-87.50, y=32.00, z=354.50], EntityChicken['Chicken'/622, l='MpServer', x=-61.50, y=67.00, z=406.50], EntitySkeleton['Skeleton'/1903, l='MpServer', x=-143.50, y=45.00, z=308.50], EntityChicken['Chicken'/623, l='MpServer', x=-62.50, y=67.00, z=406.50], EntityFishSalmon['Salmon'/2672, l='MpServer', x=-99.50, y=59.00, z=312.50], EntityPig['Pig'/624, l='MpServer', x=-51.75, y=68.00, z=389.94], EntityFishSalmon['Salmon'/2673, l='MpServer', x=-102.22, y=57.91, z=311.58], EntityPig['Pig'/625, l='MpServer', x=-49.50, y=68.00, z=390.50], EntitySkeleton['Skeleton'/1906, l='MpServer', x=-159.56, y=40.00, z=292.06], EntityFishSalmon['Salmon'/2674, l='MpServer', x=-102.50, y=59.00, z=308.50], EntitySkeleton['Skeleton'/1907, l='MpServer', x=-130.50, y=34.00, z=319.50], EntityFishSalmon['Salmon'/2675, l='MpServer', x=-103.50, y=59.00, z=310.50], EntityPig['Pig'/627, l='MpServer', x=-54.50, y=68.00, z=391.50], EntitySkeleton['Skeleton'/2680, l='MpServer', x=-118.50, y=26.00, z=421.50], EntityBat['Bat'/2169, l='MpServer', x=-86.52, y=34.34, z=351.46], EntitySkeleton['Skeleton'/2681, l='MpServer', x=-83.50, y=32.00, z=354.50], EntityBat['Bat'/2170, l='MpServer', x=-104.42, y=29.10, z=303.75], EntityCreeper['Creeper'/2683, l='MpServer', x=-97.50, y=42.00, z=354.50], EntityCreeper['Creeper'/1662, l='MpServer', x=-139.55, y=40.00, z=333.14], EntityCreeper['Creeper'/1663, l='MpServer', x=-143.49, y=38.00, z=331.06], EntityFishSalmon['Salmon'/1919, l='MpServer', x=-106.50, y=58.00, z=293.50], EntityFishSalmon['Salmon'/1920, l='MpServer', x=-103.50, y=58.00, z=296.50], EntitySkeleton['Skeleton'/2688, l='MpServer', x=-190.50, y=39.00, z=418.50], EntityFishSalmon['Salmon'/2690, l='MpServer', x=-102.50, y=59.00, z=293.50], EntityFishSalmon['Salmon'/2691, l='MpServer', x=-104.50, y=59.00, z=293.50], EntityBat['Bat'/2705, l='MpServer', x=-137.27, y=24.40, z=308.83], EntityZombie['Zombie'/2195, l='MpServer', x=-129.70, y=34.00, z=380.95], EntitySkeleton['Skeleton'/2197, l='MpServer', x=-128.50, y=31.00, z=345.50], EntityFishSalmon['Salmon'/2709, l='MpServer', x=-185.30, y=58.00, z=371.30], EntitySkeleton['Skeleton'/2198, l='MpServer', x=-112.50, y=22.00, z=314.50], EntityFishSalmon['Salmon'/2710, l='MpServer', x=-185.50, y=57.74, z=369.37], EntitySpider['Spider'/1943, l='MpServer', x=-138.50, y=24.00, z=311.50], EntityZombie['Zombie'/2199, l='MpServer', x=-124.50, y=34.00, z=379.50], EntitySkeleton['Skeleton'/1944, l='MpServer', x=-203.50, y=28.00, z=312.50], EntityZombie['Zombie'/2203, l='MpServer', x=-119.50, y=22.00, z=308.50], EntityBat['Bat'/2204, l='MpServer', x=-199.17, y=16.10, z=311.25], EntityZombie['Zombie'/2716, l='MpServer', x=-187.50, y=39.00, z=419.50], EntityZombie['Zombie'/2717, l='MpServer', x=-186.50, y=39.00, z=423.50], EntityZombie['Zombie'/1954, l='MpServer', x=-138.50, y=24.00, z=307.50], EntityItem['item.item.seeds'/1962, l='MpServer', x=-113.69, y=64.00, z=372.49], EntityBat['Bat'/1963, l='MpServer', x=-185.25, y=25.10, z=320.99], EntityBat['Bat'/1964, l='MpServer', x=-181.47, y=21.19, z=327.06], EntityItem['item.item.seeds'/2732, l='MpServer', x=-125.88, y=64.00, z=368.57], EntityBat['Bat'/1965, l='MpServer', x=-107.74, y=25.45, z=359.17], EntityItem['item.item.seeds'/2734, l='MpServer', x=-124.02, y=64.00, z=372.91], EntitySpider['Spider'/1977, l='MpServer', x=-148.50, y=58.00, z=299.50], EntityCreeper['Creeper'/1984, l='MpServer', x=-152.50, y=31.00, z=355.50], EntityZombie['Zombie'/2240, l='MpServer', x=-125.50, y=31.00, z=344.50], EntityZombie['Zombie'/2241, l='MpServer', x=-91.50, y=28.00, z=334.50], EntityBat['Bat'/2243, l='MpServer', x=-198.20, y=15.02, z=312.70], EntityBat['Bat'/2244, l='MpServer', x=-84.98, y=28.03, z=426.85], EntitySkeleton['Skeleton'/2248, l='MpServer', x=-156.50, y=32.00, z=359.50], EntityFishCod['Cod'/2761, l='MpServer', x=-190.50, y=61.00, z=369.50], EntityFishCod['Cod'/2762, l='MpServer', x=-186.50, y=61.00, z=371.50], EntityFishCod['Cod'/2763, l='MpServer', x=-184.50, y=61.00, z=376.50], EntityPlayerSP['MLMII'/380, l='MpServer', x=-126.10, y=64.00, z=370.91], EntityZombie['Zombie'/1232, l='MpServer', x=-153.50, y=31.00, z=357.50], EntityZombie['Zombie'/2512, l='MpServer', x=-99.50, y=35.00, z=343.50], EntitySkeleton['Skeleton'/2513, l='MpServer', x=-102.50, y=33.00, z=333.50], EntityCreeper['Creeper'/1491, l='MpServer', x=-165.15, y=37.00, z=338.51], EntityFishCod['Cod'/2006, l='MpServer', x=-117.50, y=60.00, z=289.50], EntityFishCod['Cod'/2007, l='MpServer', x=-113.50, y=60.00, z=290.50], EntitySpider['Spider'/2265, l='MpServer', x=-72.23, y=18.00, z=386.57], EntityEnderman['Enderman'/1251, l='MpServer', x=-119.52, y=58.00, z=436.58], EntityItem['item.item.seeds'/1785, l='MpServer', x=-184.12, y=63.00, z=359.06], EntityZombie['Zombie'/1788, l='MpServer', x=-205.37, y=23.00, z=362.17], EntityBat['Bat'/2045, l='MpServer', x=-116.44, y=23.87, z=345.86], EntityBat['Bat'/2046, l='MpServer', x=-110.36, y=22.02, z=348.84]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 17677850360 bytes (16858 MB) / 20300431360 bytes (19360 MB) up to 25769803776 bytes (24576 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UseG1GC -Xmx24G -Xms16G -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 13, tcache: 95, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2836 Optifine OptiFine_1.12.2_HD_U_E3 36 mods loaded, 36 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                    | Version            | Source                                   | Signature                                |
	|:------ |:--------------------- |:------------------ |:---------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft             | 1.12.2             | minecraft.jar                            | None                                     |
	| LCHIJA | mcp                   | 9.42               | minecraft.jar                            | None                                     |
	| LCHIJA | FML                   | 8.0.99.99          | forge-1.12.2-14.23.5.2836.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                 | 14.23.5.2836       | forge-1.12.2-14.23.5.2836.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | gender                | 1.2.9              | [1.12.2]Gender-1.2.9.jar                 | None                                     |
	| LCHIJA | jei                   | 4.15.0.268         | jei_1.12.2-4.15.0.268.jar                | None                                     |
	| LCHIJA | quark                 | r1.5-150           | Quark-r1.5-150.jar                       | None                                     |
	| LCHIJA | autoreglib            | 1.3-28             | AutoRegLib-1.3-28.jar                    | None                                     |
	| LCHIJA | baubles               | 1.5.2              | Baubles-1.12-1.5.2.jar                   | None                                     |
	| LCHIJA | betteradvancements    | 0.1.0.77           | BetterAdvancements-1.12.2-0.1.0.77.jar   | None                                     |
	| LCHIJA | betterhud             | 1.4                | betterhud-1.12.2-1.4.jar                 | None                                     |
	| LCHIJA | borntobe              | @VERSION@          | borntobe-1.12.2-1.0.jar                  | None                                     |
	| LCHIJA | cleanview             | 1.12.2-v1b         | CleanView-1.12.2-v1b.jar                 | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LCHIJA | cosmeticarmorreworked | 1.12.2-v4a         | CosmeticArmorReworked-1.12.2-v4a.jar     | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LCHIJA | ctm                   | MC1.12.2-0.3.3.22  | CTM-MC1.12.2-0.3.3.22.jar                | None                                     |
	| LCHIJA | forgelin              | 1.8.2              | Forgelin-1.8.2.jar                       | None                                     |
	| LCHIJA | iblis_headshots       | 1.2.3              | iblis-headshots-1.2.3.jar                | None                                     |
	| LCHIJA | ic2                   | 2.8.149-ex112      | industrialcraft-2-2.8.149-ex112.jar      | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | jeid                  | 1.0.2-26           | JustEnoughIDs-1.0.2-26.jar               | None                                     |
	| LCHIJA | jeidsi                | 1.2.0.22           | jeidsi-1.2.0.22.jar                      | None                                     |
	| LCHIJA | jaff                  | 1.7_for_1.12       | JustAFewFish-1.7_for_1.12.jar            | None                                     |
	| LCHIJA | keywizard             | 1.12.2-1.5.6       | keywizard-1.12.2-1.5.6.jar               | None                                     |
	| LCHIJA | librarianlib          | 4.17               | librarianlib-1.12.2-4.17.jar             | None                                     |
	| LCHIJA | radixcore             | 1.12.x-2.2.1       | RadixCore-1.12.x-2.2.1-universal.jar     | None                                     |
	| LCHIJA | mca                   | 1.12.2-5.3.1       | MCA-1.12.x-5.3.1-universal.jar           | None                                     |
	| LCHIJA | mendinggems           | 1.0.0              | MendingGems-1.12.2-1.0.0.jar             | None                                     |
	| LCHIJA | naturalabsorption     | 1.0.0_for_mc1.12.2 | naturalabsorption-1.0.0_for_mc1.12.2.jar | None                                     |
	| LCHIJA | recipehandler         | 0.13               | NoMoreRecipeConflict-0.13(1.12.2).jar    | None                                     |
	| LCHIJA | quarkoddities         | 1                  | QuarkOddities-1.12.2.jar                 | None                                     |
	| LCHIJA | ruins                 | 17.1               | Ruins-1.12.2.jar                         | None                                     |
	| LCHIJA | scp                   | 2.1.1              | SCP+Lockdown-1.12.2-2.1.1-beta.jar       | None                                     |
	| LCHIJA | torohud               | 1.12.2-5           | torohud-1.12.2-5.jar                     | None                                     |
	| LCHIJA | vtt                   | 0.6.4              | VillagerTrades-1.12-0.6.4.jar            | None                                     |
	| LCHIJA | waystones             | 4.0.67             | Waystones_1.12.2-4.0.67.jar              | None                                     |
	| LCHIJA | wizardry              | 0.10.0             | wizardry-0.10.0.jar                      | None                                     |
	| LCHIJA | librarianliblate      | 4.17               | librarianlib-1.12.2-4.17.jar             | None                                     |

	Loaded coremods (and transformers): 
Quark Plugin (Quark-r1.5-150.jar)
  vazkii.quark.base.asm.ClassTransformer
GenderLoadingPlugin ([1.12.2]Gender-1.2.9.jar)
  com.github.ipixeli.gender.coremod.GenderClassTransformer
JEIDsILoadingPlugin (jeidsi-1.2.0.22.jar)
  
Wizardry Plugin (wizardry-0.10.0.jar)
  com.teamwizardry.wizardry.asm.WizardryTransformer
JEIDLoadingPlugin (JustEnoughIDs-1.0.2-26.jar)
  org.dimdev.jeid.JEIDTransformer
ForgelinPlugin (Forgelin-1.8.2.jar)
  
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
LibrarianLib Plugin (librarianlib-1.12.2-4.17.jar)
  com.teamwizardry.librarianlib.asm.LibLibTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 419.67' Renderer: 'GeForce GTX TITAN/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2836
	LWJGL: 2.9.4
	OpenGL: GeForce GTX TITAN/PCIe/SSE2 GL version 4.6.0 NVIDIA 419.67, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: No+More+Mumbles.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x Intel(R) Core(TM) i7-3930K CPU @ 3.20GHz

**Comment by MLMII** [comment]
librarianlib-1.12.2-4.18-fat

Seems to have fixed the issue, thanks.
