### ISSUE TITLE
Server crash on "Cannot add types to unregistered biome"

### ISSUE THREAD

**Issue by zkxs** [TeamWizardry/Wizardry#296]
### What happened
I believe (not 100% sure) I got teleported to a different dimension. It looks like on my first tick there the server crashed. The server restarts just fine, until I log back in, at which point it ticks and crashes again.

### Versions
Minecraft: 1.12.2  
Forge: 14.23.5.2838
Wizardry: 0.10.8
LibrarianLib: 1.12.2-4.19.2

### Stacktrace
```
java.lang.IllegalArgumentException: Cannot add types to unregistered biome com.teamwizardry.wizardry.common.world.biome.BiomeTorikki@d3f9a47
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191)
        at net.minecraftforge.common.BiomeDictionary.addTypes(BiomeDictionary.java:185)
        at net.minecraftforge.common.BiomeDictionary.makeBestGuess(BiomeDictionary.java:285)
        at net.minecraftforge.common.BiomeDictionary.ensureHasTypes(BiomeDictionary.java:382)
        at net.minecraftforge.common.BiomeDictionary.getTypes(BiomeDictionary.java:217)
        at net.minecraftforge.common.BiomeDictionary.hasType(BiomeDictionary.java:245)
        at cofh.cofhworld.data.biome.BiomeInfo.isBiomeEqual(BiomeInfo.java:51)
        at cofh.cofhworld.data.biome.BiomeInfoSet.contains(BiomeInfoSet.java:77)
        at cofh.cofhworld.world.distribution.Distribution.canGenerateInBiome(Distribution.java:83)
        at cofh.cofhworld.world.distribution.DistributionUniform.generateFeature(DistributionUniform.java:46)
        at cofh.cofhworld.world.distribution.Distribution.generateFeature(Distribution.java:110)
        at cofh.cofhworld.init.WorldHandler.generateWorld(WorldHandler.java:319)
        at cofh.cofhworld.init.WorldHandler.generate(WorldHandler.java:303)
        at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
        at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1020)
        at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:999)
        at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
        at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
        at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
        at java.lang.Thread.run(Thread.java:748)
```

Full crashlog: https://gist.github.com/zkxs/0eb66f83d3316e1a73bdf3fc1bb00348

**Comment by murapix** [comment]
Yeah, this bug's a really weird one, cause the "unregistered biome" it's talking about is fully registered. I remember this issue popping up before, I think with us and Thaumcraft, but I don't remember the solution.

**Comment by zkxs** [comment]
My temporary workaround was editing my playerdata file to move me out of the torikki dimension (34 for me) and back into the overworld (0). If anyone ever ends up in dimension 34 again I imagine it'll crash, but for now we're fine.

**Comment by SwissCheese5** [comment]
I believe I fixed this in dev

**Comment by PhotonChaos** [comment]
This isn't something we can really fix at the moment. Stay away from Torikki though. If this issue persists without a player visiting that dimension somehow, leave a comment on this issue.
