### ISSUE TITLE
My game always crash when i use a spell or make a spell

### ISSUE THREAD

**Issue by unknowndude45731** [TeamWizardry/Wizardry#299]
here is the crash report:---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Shadowfacts-Forgelin-1.12.2.jar)
  Wizardry Plugin (wizardry-0.10.8.jar)
  LibrarianLib Plugin (LibrarianLib-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Oh - I know what I did wrong!

Time: 8/7/19 11:32 PM
Description: Unexpected error

java.lang.ClassCastException: Cannot cast java.lang.Double to com.teamwizardry.librarianlib.features.math.Vec2d
	at java.lang.invoke.MethodHandleImpl.newClassCastException(Unknown Source)
	at java.lang.invoke.MethodHandleImpl.castReference(Unknown Source)
	at com.teamwizardry.librarianlib.features.methodhandles.InvocationWrapper.invoke(InvocationWrapper.java:21)
	at com.teamwizardry.librarianlib.features.methodhandles.MethodHandleHelper$wrapperForMethod$1.invoke(MethodHandleHelper.kt:180)
	at com.teamwizardry.librarianlib.features.methodhandles.MethodHandleHelper$wrapperForMethod$1.invoke(MethodHandleHelper.kt:15)
	at com.teamwizardry.librarianlib.features.animator.FieldListItem$rootGetter$2$1.invoke(KeyPathGetterSetterGenerator.kt:369)
	at com.teamwizardry.librarianlib.features.animator.FieldListItem$rootSetter$2$1.invoke(KeyPathGetterSetterGenerator.kt:246)
	at com.teamwizardry.librarianlib.features.animator.FieldListItem$rootSetter$2$1.invoke(KeyPathGetterSetterGenerator.kt:247)
	at com.teamwizardry.librarianlib.features.animator.KeyPathGetterSetterGeneratorKt$generateGetterAndSetterForKeyPath$1.invoke(KeyPathGetterSetterGenerator.kt:89)
	at com.teamwizardry.librarianlib.features.animator.KeyPathGetterSetterGeneratorKt$generateGetterAndSetterForKeyPath$1.invoke(KeyPathGetterSetterGenerator.kt)
	at com.teamwizardry.librarianlib.features.animator.AnimatableProperty.set(AnimatableProperty.kt:27)
	at com.teamwizardry.librarianlib.features.animator.animations.BasicAnimation.update(BasicAnimation.kt:32)
	at com.teamwizardry.librarianlib.features.animator.Animator.update$librarianlib_1_12_2(Animator.kt:146)
	at com.teamwizardry.librarianlib.features.animator.Animator$Companion.renderTick(Animator.kt:205)
	at com.teamwizardry.librarianlib.features.animator.Animator.renderTick(Animator.kt)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_27_Animator_renderTick_RenderTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onRenderTickStart(FMLCommonHandler.java:355)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.lang.invoke.MethodHandleImpl.newClassCastException(Unknown Source)
	at java.lang.invoke.MethodHandleImpl.castReference(Unknown Source)
	at com.teamwizardry.librarianlib.features.methodhandles.InvocationWrapper.invoke(InvocationWrapper.java:21)
	at com.teamwizardry.librarianlib.features.methodhandles.MethodHandleHelper$wrapperForMethod$1.invoke(MethodHandleHelper.kt:180)
	at com.teamwizardry.librarianlib.features.methodhandles.MethodHandleHelper$wrapperForMethod$1.invoke(MethodHandleHelper.kt:15)
	at com.teamwizardry.librarianlib.features.animator.FieldListItem$rootGetter$2$1.invoke(KeyPathGetterSetterGenerator.kt:369)
	at com.teamwizardry.librarianlib.features.animator.FieldListItem$rootSetter$2$1.invoke(KeyPathGetterSetterGenerator.kt:246)
	at com.teamwizardry.librarianlib.features.animator.FieldListItem$rootSetter$2$1.invoke(KeyPathGetterSetterGenerator.kt:247)
	at com.teamwizardry.librarianlib.features.animator.KeyPathGetterSetterGeneratorKt$generateGetterAndSetterForKeyPath$1.invoke(KeyPathGetterSetterGenerator.kt:89)
	at com.teamwizardry.librarianlib.features.animator.KeyPathGetterSetterGeneratorKt$generateGetterAndSetterForKeyPath$1.invoke(KeyPathGetterSetterGenerator.kt)
	at com.teamwizardry.librarianlib.features.animator.AnimatableProperty.set(AnimatableProperty.kt:27)
	at com.teamwizardry.librarianlib.features.animator.animations.BasicAnimation.update(BasicAnimation.kt:32)
	at com.teamwizardry.librarianlib.features.animator.Animator.update$librarianlib_1_12_2(Animator.kt:146)
	at com.teamwizardry.librarianlib.features.animator.Animator$Companion.renderTick(Animator.kt:205)
	at com.teamwizardry.librarianlib.features.animator.Animator.renderTick(Animator.kt)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_27_Animator_renderTick_RenderTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['unknowndude45731'/52, l='MpServer', x=385.89, y=4.00, z=935.70]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (385,4,930), Chunk: (at 1,0,2 in 24,58; contains blocks 384,0,928 to 399,255,943), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
	Level time: 10624 game time, 10624 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 13 total; [EntityPig['Pig'/15, l='MpServer', x=319.50, y=4.00, z=921.14], EntityDonkey['Donkey'/16, l='MpServer', x=319.85, y=4.00, z=924.84], EntityPig['Pig'/17, l='MpServer', x=320.00, y=4.00, z=925.90], EntityPig['Pig'/18, l='MpServer', x=311.74, y=4.00, z=925.43], EntityChicken['Chicken'/19, l='MpServer', x=313.80, y=4.00, z=1002.14], EntityPig['Pig'/20, l='MpServer', x=333.40, y=4.00, z=986.69], EntityCow['Cow'/21, l='MpServer', x=323.37, y=4.00, z=1004.17], EntityPig['Pig'/22, l='MpServer', x=328.42, y=4.00, z=996.74], EntitySlime['Slime'/64920, l='MpServer', x=389.51, y=5.10, z=875.76], EntitySlime['Slime'/51107, l='MpServer', x=408.68, y=4.00, z=976.36], EntitySlime['Slime'/72357, l='MpServer', x=449.86, y=4.00, z=1001.05], EntityPlayerSP['unknowndude45731'/52, l='MpServer', x=385.89, y=4.00, z=935.70], EntitySlime['Slime'/43701, l='MpServer', x=362.89, y=4.00, z=946.96]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 201676336 bytes (192 MB) / 631791616 bytes (602 MB) up to 1038876672 bytes (990 MB)
	JVM Flags: 8 total; -XX:+UseConcMarkSweepGC -XX:-UseAdaptiveSizePolicy -XX:+CMSParallelRemarkEnabled -XX:+ParallelRefProcEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseCMSInitiatingOccupancyOnly -Xmx1024M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2837 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID               | Version      | Source                          | Signature                                |
	|:------ |:---------------- |:------------ |:------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft        | 1.12.2       | minecraft.jar                   | None                                     |
	| LCHIJA | mcp              | 9.42         | minecraft.jar                   | None                                     |
	| LCHIJA | FML              | 8.0.99.99    | forge-1.12.2-14.23.5.2837.jar   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge            | 14.23.5.2837 | forge-1.12.2-14.23.5.2837.jar   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forgelin         | 1.8.2        | Shadowfacts-Forgelin-1.12.2.jar | None                                     |
	| LCHIJA | librarianlib     | 4.17         | LibrarianLib-1.12.2.jar         | None                                     |
	| LCHIJA | wizardry         | 0.10.8       | wizardry-0.10.8.jar             | None                                     |
	| LCHIJA | librarianliblate | 4.17         | LibrarianLib-1.12.2.jar         | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (Shadowfacts-Forgelin-1.12.2.jar)
  
Wizardry Plugin (wizardry-0.10.8.jar)
  com.teamwizardry.wizardry.asm.WizardryTransformer
LibrarianLib Plugin (LibrarianLib-1.12.2.jar)
  com.teamwizardry.librarianlib.asm.LibLibTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '3.3.0' Renderer: 'Quadro FX 570/PCIe/SSE2'
	Launched Version: Forge 1.12.2
	LWJGL: 2.9.4
	OpenGL: Quadro FX 570/PCIe/SSE2 GL version 3.3.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/Eagle Nebula Sky 1.13+.zip (incompatible), programer_art
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Xeon(R) CPU W3530 @ 2.80GHz

**Comment by PhotonChaos** [comment]
Unfortunately, we cannot reproduce this bug. If you are still experiencing it with the _newest_ versions of Wizardry and LibLib, please comment on this issue with steps to reproduce.
