### ISSUE TITLE
Spongeforge server crash when installing mod: Cannot add types to unregistered biome com.teamwizardry.wizardry.common.world.biome.BiomeTorikki

### ISSUE THREAD

**Issue by Nox13last** [TeamWizardry/Wizardry#307]
MC 1.12.2
Forgelin-1.8.4.jar
wizardry-0.10.8.jar
librarianlib-1.12.2-4.19.2-release.jar
forge-1.12.2-14.23.5.2844-universal.jar

[crash-2019-09-27_12.33.30-server.txt](https://github.com/TeamWizardry/Wizardry/files/3664342/crash-2019-09-27_12.33.30-server.txt)

```
java.lang.IllegalArgumentException: Cannot add types to unregistered biome com.teamwizardry.wizardry.common.world.biome.BiomeTorikki@2c28610a
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191)
    at net.minecraftforge.common.BiomeDictionary.addTypes(BiomeDictionary.java:185)
    at net.minecraftforge.common.BiomeDictionary.makeBestGuess(BiomeDictionary.java:285)
    at net.minecraftforge.common.BiomeDictionary.ensureHasTypes(BiomeDictionary.java:382)
    at net.minecraftforge.common.BiomeDictionary.getTypes(BiomeDictionary.java:217)
    at net.minecraftforge.common.BiomeDictionary.hasType(BiomeDictionary.java:245)
    at cofh.cofhworld.data.biome.BiomeInfo.isBiomeEqual(BiomeInfo.java:51)
    at cofh.cofhworld.data.biome.BiomeInfoSet.contains(BiomeInfoSet.java:77)
    at cofh.cofhworld.world.distribution.Distribution.canGenerateInBiome(Distribution.java:83)
    at cofh.cofhworld.world.distribution.DistributionUniform.generateFeature(DistributionUniform.java:46)
    at cofh.cofhworld.world.distribution.Distribution.generateFeature(Distribution.java:110)
    at cofh.cofhworld.init.WorldHandler.generateWorld(WorldHandler.java:319)
    at cofh.cofhworld.init.WorldHandler.generate(WorldHandler.java:303)
    at net.minecraftforge.fml.common.registry.GameRegistry.redirect$onGenerateWorld$zzd000(GameRegistry.java:571)
    at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
    at net.minecraft.world.chunk.Chunk.populate(Chunk.java:1020)
    at net.minecraft.world.chunk.Chunk.populate(Chunk.java:999)
    at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:157)
    at net.minecraft.world.World.getChunk(World.java:310)
    at net.minecraft.world.World.getChunk(World.java:305)
    at net.minecraft.world.WorldServer.getBlockState(WorldServer.java:3500)
    at com.mcmoddev.orespawn.worldgen.FlatBedrock.genBottomPlate(FlatBedrock.java:58)
    at com.mcmoddev.orespawn.worldgen.FlatBedrock.retrogen(FlatBedrock.java:40)
    at com.mcmoddev.orespawn.EventHandlers.worldTick(EventHandlers.java:222)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_638_EventHandlers_worldTick_WorldTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:756)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:706)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:274)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:776)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)
```
I hear this issue is due to some conflict with Thaumcraft, and that this issue was being worked on in dev. It loads to main menu fine, but the server gets as far as beginning to generate worlds before it crashes ungracefully.

Is there any recourse at this time, because Thaumcraft is getting stale and there's still no sign of Ars Magica 3.

**Comment by PhotonChaos** [comment]
Thank you for the detailed post! Unfortunately, this does not seem like an issue with the Wizardry mod, it is more likely something wrong with COFH, Sponge, or Orespawn. You should try posting this on their respective issue trackers, and if they point you back here with what we could do to fix it, comment it on this issue.
