### ISSUE TITLE
Crash when using stick

### ISSUE THREAD

**Issue by zendrique** [TeamWizardry/Wizardry#308]
`java.lang.NoSuchMethodError: net.minecraft.util.math.AxisAlignedBB.<init>(Lnet/minecraft/util/math/Vec3d;Lnet/minecraft/util/math/Vec3d;)V
	at com.teamwizardry.wizardry.common.module.effects.ModuleEffectLowGravity.onRunZone(ModuleEffectLowGravity.java:61)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at com.teamwizardry.wizardry.api.spell.module.ModuleOverrideHandler$OverridePointer.invoke(ModuleOverrideHandler.java:494)
	at com.teamwizardry.wizardry.api.spell.module.ModuleOverrideHandler$OverrideInvoker.invoke(ModuleOverrideHandler.java:687)
	at com.sun.proxy.$Proxy156.onRunZone(Unknown Source)
	at com.teamwizardry.wizardry.common.module.shapes.ModuleShapeZone.run(ModuleShapeZone.java:84)
	at com.teamwizardry.wizardry.common.module.shapes.ModuleShapeZone.run(ModuleShapeZone.java:47)
	at com.teamwizardry.wizardry.api.spell.module.ModuleInstanceShape.run(ModuleInstanceShape.java:52)
	at com.teamwizardry.wizardry.api.spell.module.ModuleInstance.internalCastSpell(ModuleInstance.java:520)
	at com.teamwizardry.wizardry.api.spell.module.ModuleInstance.castSpell(ModuleInstance.java:506)
	at com.teamwizardry.wizardry.api.spell.SpellRing.runSpellRing(SpellRing.java:231)
	at com.teamwizardry.wizardry.api.spell.SpellRing.runSpellRing(SpellRing.java:235)
	at com.teamwizardry.wizardry.api.SpellObjectManager$LingeringObject.tick(SpellObjectManager.java:93)
	at com.teamwizardry.wizardry.api.lifetimeobject.LifetimeObjectManager.tick(LifetimeObjectManager.java:38)
	at com.teamwizardry.wizardry.api.SpellObjectManager.tick(SpellObjectManager.java:56)
	at com.teamwizardry.wizardry.common.core.SpellTicker.tick(SpellTicker.java:39)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_175_SpellTicker_tick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:752)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:702)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:274)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:776)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at ### java.lang.Thread.run(Thread.java:745)`

**Comment by PhotonChaos** [comment]
Sorry, but there's not enough info here for us to fix the issue! If you are still having this issue and can provide us steps to reliably reproduce it, please comment that on this thread and we will try our best to fix it.
