### ISSUE TITLE
Allow mana pool generation to be turned off.

### ISSUE THREAD

**Issue by Dilnu** [TeamWizardry/Wizardry#61]
Hi, I was trying to replace mana pool generation with either a crafting recipe for liquid mana or a custom world generator. I tried setting the config to 0 which works in most mods but in this case it resulted in the game crashing.

`java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388) ~[?:1.8.0_121]
	at com.teamwizardry.wizardry.common.world.WorldGenManaLake.generate(WorldGenManaLake.java:23) ~[WorldGenManaLake.class:?]
	at com.teamwizardry.wizardry.common.world.GenHandler.generateMana(GenHandler.java:24) ~[GenHandler.class:?]
	at com.teamwizardry.wizardry.common.world.GenHandler.generate(GenHandler.java:31) ~[GenHandler.class:?]`

**Comment by murapix** [comment]
Ready for the next build.
